use senior_assassin;
truncate players;

insert into players (pla_name, pla_instagram) values ('Dylan Gaine', 'Dylangaine13');
insert into players (pla_name, pla_instagram) values ('Brodie Carroll', 'Brod7e');
insert into players (pla_name, pla_instagram) values ('Samantha Burke', '_samanthaburke_');
insert into players (pla_name, pla_instagram) values ('Max Aiello', 'max_aiello');
insert into players (pla_name, pla_instagram) values ('Maddie Poirier', 'maddiepoirierr');
insert into players (pla_name, pla_instagram) values ('Sophie Marshall-Pelayo', 'sophiee_mp');
insert into players (pla_name, pla_instagram) values ('Gina Mignosa', 'Gina_mignosa ');
insert into players (pla_name, pla_instagram) values ('Ella Duff', 'elladufff');
insert into players (pla_name, pla_instagram) values ('Andrew Keegan', 'andydrewkeegan');
insert into players (pla_name, pla_instagram) values ('Shane Coleman', 'scoleman66');
insert into players (pla_name, pla_instagram) values ('Ava Toglia', 'avatogllia ');
insert into players (pla_name, pla_instagram) values ('David Quinlan', 'davidquinlan');
insert into players (pla_name, pla_instagram) values ('Lilah Wheeler', 'lilah.wheeler');
insert into players (pla_name, pla_instagram) values ('Aria Arbia', 'ariaarbia');
insert into players (pla_name, pla_instagram) values ('Rachael Reynolds', '_rachaelreynoldss');
insert into players (pla_name, pla_instagram) values ('Charlie Carroll', 'c.carroll_23');
insert into players (pla_name, pla_instagram) values ('Ava Curran', 'ava.currann');
insert into players (pla_name, pla_instagram) values ('Lauren Cusick', 'laurencusick');
insert into players (pla_name, pla_instagram) values ('Mary Grace Lynch', 'marygrace.lynch');
insert into players (pla_name, pla_instagram) values ('Meredith DeCoste', '617-777-5094');
insert into players (pla_name, pla_instagram) values ('Gabrielle Guy', 'gabbyguyy ');
insert into players (pla_name, pla_instagram) values ('Alexa Rowe', 'alexarowee');
insert into players (pla_name, pla_instagram) values ('Ashley Little', '_ashleylittlee');
insert into players (pla_name, pla_instagram) values ('Lexi Rondeau', 'lexi.rondeau');
insert into players (pla_name, pla_instagram) values ('Hayley Cabral', 'hayley.cabral');
insert into players (pla_name, pla_instagram) values ('Matthew Fortuna', 'matt4tuna33 ');
insert into players (pla_name, pla_instagram) values ('Kylie Handrahan', 'kyliehandrahan ');
insert into players (pla_name, pla_instagram) values ('Mary Elliott', 'Maryyelliott');
insert into players (pla_name, pla_instagram) values ('Maeve Sullivan', 'maeve_sullivann');
insert into players (pla_name, pla_instagram) values ('Jake Peterson', 'jake22peterson ');
insert into players (pla_name, pla_instagram) values ('Danny Tawa', 'Dannytawa12');
insert into players (pla_name, pla_instagram) values ('Luke Segalla', 'Luke_segalla');
insert into players (pla_name, pla_instagram) values ('Sarah Long', 'sarah.l2023');
insert into players (pla_name, pla_instagram) values ('Nick Freel', 'nickkfreel');
insert into players (pla_name, pla_instagram) values ('Donovan Ryan', 'donovan.ryan44');
insert into players (pla_name, pla_instagram) values ('Christian Carlson',  'christiancarlson24');
insert into players (pla_name, pla_instagram) values ('Olivia Curran', '_oliviacurran');
insert into players (pla_name, pla_instagram) values ('Gavin Swenson', 'gavin.swen ');
insert into players (pla_name, pla_instagram) values ('Ryan Jones', 'rdjones2805');
insert into players (pla_name, pla_instagram) values ('Jake Pelish', 'jpel5');
insert into players (pla_name, pla_instagram) values ('John Ryan', 'john.ryan143');
insert into players (pla_name, pla_instagram) values ('Peyton Noonan', 'peyton_noonan');
insert into players (pla_name, pla_instagram) values ('AJ Leone', 'ajl_718');
insert into players (pla_name, pla_instagram) values ('Owen Paul', 'Owenp_1');
insert into players (pla_name, pla_instagram) values ('Abby Armstrong', 'abby_armstrongg');
insert into players (pla_name, pla_instagram) values ('Chase Puleo', 'chase.puleo');
insert into players (pla_name, pla_instagram) values ('Jack Douglas', 'jackdouglas_4');
insert into players (pla_name, pla_instagram) values ('Anna Mahoney', 'anna.mahoneyy');
insert into players (pla_name, pla_instagram) values ('Max Cunniff', 'dieselmax1987');
insert into players (pla_name, pla_instagram) values ('Brian Bellerby', 'brianbellerby');
insert into players (pla_name, pla_instagram) values ('Jay LaFreniere', 'jaylafreniere14');
insert into players (pla_name, pla_instagram) values ('Jimmy Godin', 'jimmy_g333');
insert into players (pla_name, pla_instagram) values ('Gianna Puzzangara', 'gianna.puzzangara');
insert into players (pla_name, pla_instagram) values ('Kathryn Shields', 'kathryn.shields');
insert into players (pla_name, pla_instagram) values ('Riley Worrall', 'riley.worrall');
insert into players (pla_name, pla_instagram) values ('Patrick Jones', 'pat.jonez');
insert into players (pla_name, pla_instagram) values ('Joe Clasby', 'joeclasby');
insert into players (pla_name, pla_instagram) values ('Brendan O’Neil', 'brendan.oneil10');
insert into players (pla_name, pla_instagram) values ('Ella Heyl', 'ellaheyl');
insert into players (pla_name, pla_instagram) values ('Liam Monahan', '_liammonahan_');
insert into players (pla_name, pla_instagram) values ('Ryan Freedman', 'ry.freed');
insert into players (pla_name, pla_instagram) values ('Ben Hickey', 'ben_hickey3');
insert into players (pla_name, pla_instagram) values ('Seth Willoughby', 'Swankwilloughby');
insert into players (pla_name, pla_instagram) values ('Mia Pongratz', 'mpongratz1 ');
insert into players (pla_name, pla_instagram) values ('Andrew Holmes', 'andrew_holmes4');
insert into players (pla_name, pla_instagram) values ('Harrison Brewster', 'harrison.brewster_');
insert into players (pla_name, pla_instagram) values ('Ryan Coutts', 'ryancoutts11');
insert into players (pla_name, pla_instagram) values ('Mary Carven', 'marycarven');
insert into players (pla_name, pla_instagram) values ('Holly Rossi', 'holly.rossi');
insert into players (pla_name, pla_instagram) values ('Brady Wilson', 'BradyWilsonnn');
insert into players (pla_name, pla_instagram) values ('Julia Sledziewski', 'julia.sled');
insert into players (pla_name, pla_instagram) values ('Joe Young', 'MightyJoeYoung99 ');
insert into players (pla_name, pla_instagram) values ('Morgan Ceurvels', 'mceurvels');
insert into players (pla_name, pla_instagram) values ('Cate Migre', 'catemigre');
insert into players (pla_name, pla_instagram) values ('Annie Straut', 'annie.straut ');
insert into players (pla_name, pla_instagram) values ('Mike DeMayo', 'mikedemayo7');
insert into players (pla_name, pla_instagram) values ('Colin Killgoar', 'Colinkillgoar');
insert into players (pla_name, pla_instagram) values ('Cam Barron', 'Camcbarron11');
insert into players (pla_name, pla_instagram) values ('Declan King', 'declan_king.20');
insert into players (pla_name, pla_instagram) values ('Joe Curran', 'joecurran6');
insert into players (pla_name, pla_instagram) values ('Jackson Snyder', 'Jsnyder904');
insert into players (pla_name, pla_instagram) values ('Connor Currie', 'connorcurrie_');
insert into players (pla_name, pla_instagram) values ('Devin Benjamin', 'devin.benjamin');
insert into players (pla_name, pla_instagram) values ('Colin DiTullio', 'colin.ditullio');
insert into players (pla_name, pla_instagram) values ('Griffin Gasdia', 'griffingasdia');
insert into players (pla_name, pla_instagram) values ('Teddy McCrann', 'teddymccrann');
insert into players (pla_name, pla_instagram) values ('Bobby Delkouras', 'bobby.del29');
insert into players (pla_name, pla_instagram) values ('Ellasyn Murphy', 'ellasyn.murphy');
insert into players (pla_name, pla_instagram) values ('Bree Cole', 'breecole077');
insert into players (pla_name, pla_instagram) values ('Noah Hofeman', 'Noah_hofeman ');
insert into players (pla_name, pla_instagram) values ('Jillian Farrell', 'Jillian.farrelll');
insert into players (pla_name, pla_instagram) values ('Matt Connerty', 'matt.connerty10');
insert into players (pla_name, pla_instagram) values ('Caleb Lawrence', 'caleb_lawrence23');
insert into players (pla_name, pla_instagram) values ('Owen Carolan', 'owencarolan');
insert into players (pla_name, pla_instagram) values ('Fiza Mehmood', 'fizamehmood123');
insert into players (pla_name, pla_instagram) values ('Kaya Bianculli', 'kaya.bianculli');
insert into players (pla_name, pla_instagram) values ('Mia Nofi', 'mianofi');
insert into players (pla_name, pla_instagram) values ('Ned McCann', 'nedmccann_');
insert into players (pla_name, pla_instagram) values ('Gina Avitable', 'giinaburkee');
insert into players (pla_name, pla_instagram) values ('Sydney Currie', 'sydneycurrie_');
insert into players (pla_name, pla_instagram) values ('Ethan Nosek', 'ethan_nosek');
insert into players (pla_name, pla_instagram) values ('Liam Joy', 'liamjoy17');
insert into players (pla_name, pla_instagram) values ('Cullen Burke', 'cullen.burke');
insert into players (pla_name, pla_instagram) values ('Ben Lines', 'ben_lines_');
insert into players (pla_name, pla_instagram) values ('Charles Wood', 'alex.wood___');
insert into players (pla_name, pla_instagram) values ('Caitlyn Jordan', 'caitlynjordan14');
insert into players (pla_name, pla_instagram) values ('Leyton Siew', 'lsiew23');
insert into players (pla_name, pla_instagram) values ('Dennis sacco', 'dennis.sacco22');
insert into players (pla_name, pla_instagram) values ('Tyler Richards', 'tyler.richards.2');
insert into players (pla_name, pla_instagram) values ('Erin Shea', 'erinn.shea');
insert into players (pla_name, pla_instagram) values ('Jack Sullivan', 'Jacksullivvan');
insert into players (pla_name, pla_instagram) values ('Bella Pineau', 'bella.pineau');
insert into players (pla_name, pla_instagram) values ('Joey Montoya', 'joeymontoya_');
insert into players (pla_name, pla_instagram) values ('Paige DeCoste', 'decoste_paige');
insert into players (pla_name, pla_instagram) values ('Cailyn McCarthy', 'cailynmccarthy_');
insert into players (pla_name, pla_instagram) values ('Cassie Lopes', 'cassie_lopes17');